import { GridRowsProp } from "@mui/x-data-grid";

export const rows: GridRowsProp = [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      status: "Active",
      role: "1",
      joined: "2021-01-15",
      invitedBy: "Alice Johnson",
      lastActive: "2021-09-15",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      status: "Active",
      role: "2",
      joined: "2020-11-23",
      invitedBy: "John Doe",
      lastActive: "2021-09-10",
    },
    {
      id: 3,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      status: "Inactive",
      role: "1",
      joined: "2019-05-10",
      invitedBy: "Jane Smith",
      lastActive: "2021-08-20",
    },
    {
      id: 4,
      name: "Bob Brown",
      email: "bob.brown@example.com",
      status: "Active",
      role: "2",
      joined: "2022-03-18",
      invitedBy: "Alice Johnson",
      lastActive: "2021-09-05",
    },
    {
      id: 5,
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
      status: "Inactive",
      role: "1",
      joined: "2018-07-22",
      invitedBy: "Bob Brown",
      lastActive: "2021-07-15",
    },
    {
      id: 6,
      name: "Eve Martinez",
      email: "eve.martinez@example.com",
      status: "Pending",
      role: "2",
      joined: "",
      invitedBy: "Charlie Davis",
      lastActive: "2021-06-10",
    },
  ];
  