// Nombre de las cookies
const ACCESS_TOKEN = "accessToken";
const REFRESH_TOKEN = "refreshToken";
const AUTH_TOKEN = "authToken";

const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  COLLECTIONS_EXECUTIVE: "COLLECTIONS_EXECUTIVE",
  DEBTOR: "DEBTOR",
};

export { ACCESS_TOKEN, REFRESH_TOKEN, AUTH_TOKEN, ROLES };
